// shared-core - bitdrift's common client/server libraries
// Copyright Bitdrift, Inc. All rights reserved.
//
// Use of this source code is governed by a source available license that can be found in the
// LICENSE file or at:
// https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt

#pragma once

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef const void **BDCrashWriterHandle;

/**
 * Attempt to open a writer to the specified path.
 * The writer exists on the heap and must be closed with `bdcrw_close_writer`.
 */
bool bdcrw_open_writer(BDCrashWriterHandle handle, const char *path);

void bdcrw_close_writer(BDCrashWriterHandle handle);

bool bdcrw_flush_writer(BDCrashWriterHandle handle);

bool bdcrw_write_boolean(BDCrashWriterHandle handle, bool value);

bool bdcrw_write_null(BDCrashWriterHandle handle);

bool bdcrw_write_signed(BDCrashWriterHandle handle, int64_t value);

bool bdcrw_write_unsigned(BDCrashWriterHandle handle, uint64_t value);

bool bdcrw_write_float(BDCrashWriterHandle handle, double value);

bool bdcrw_write_str(BDCrashWriterHandle handle, const char *value);

bool bdcrw_write_array_begin(BDCrashWriterHandle handle);

bool bdcrw_write_map_begin(BDCrashWriterHandle handle);

bool bdcrw_write_container_end(BDCrashWriterHandle handle);
