// capture-sdk - bitdrift's client SDK
// Copyright Bitdrift, Inc. All rights reserved.
//
// Use of this source code is governed by a source available license that can be found in the
// LICENSE file or at:
// https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt

package io.bitdrift.capture.webview

import android.annotation.SuppressLint
import android.util.Log
import android.webkit.WebView
import androidx.webkit.WebViewCompat
import androidx.webkit.WebViewFeature
import io.bitdrift.capture.Capture
import io.bitdrift.capture.Capture.LOG_TAG
import io.bitdrift.capture.CaptureRuntimeProvider
import io.bitdrift.capture.IInternalLogger
import io.bitdrift.capture.ILogger
import io.bitdrift.capture.IRuntimeProvider
import io.bitdrift.capture.LogLevel
import io.bitdrift.capture.LogType
import io.bitdrift.capture.LoggerImpl
import io.bitdrift.capture.common.RuntimeFeature
import io.bitdrift.capture.experimental.ExperimentalBitdriftApi
import io.bitdrift.capture.providers.ArrayFields
import io.bitdrift.capture.providers.fieldsOf

/**
 * Instruments WebViews to capture page loads, performance metrics, and network activity.
 *
 * WebViews can be instrumented explicitly with [instrument], or automatically by applying the
 * `io.bitdrift.capture-plugin` Gradle plugin and configuring `automaticWebViewInstrumentationMode`:
 *
 * - `FULL` instruments detected WebViews and enables JavaScript when needed.
 * - `JS_ENABLED_ONLY` instruments only WebViews where the application already enabled
 *   JavaScript; Capture does not enable it.
 * - If the property is unset, automatic WebView instrumentation is disabled.
 *
 * In every mode, Capture injects its JavaScript bridge only after the WebView is selected for instrumentation.
 */
object WebViewCapture {
    /**
     * Explicitly instruments a selected WebView.
     *
     * This call is an explicit per-WebView opt-in. Manual instrumentation always enables JavaScript when it is
     * disabled, registers the Capture bridge, and injects the monitoring script before the WebView loads content.
     * Call it before [WebView.loadUrl].
     *
     * Automatic instrumentation provides the same monitoring without an explicit call when the Capture Gradle
     * plugin configures `automaticWebViewInstrumentationMode` as `FULL` or `JS_ENABLED_ONLY`. The latter never
     * enables JavaScript on behalf of the application.
     *
     * @param webview The WebView to instrument
     */
    @ExperimentalBitdriftApi
    @JvmStatic
    fun instrument(webview: WebView) =
        WebViewCaptureInternals.instrumentInternally(
            webview,
            logger = null,
            runtimeProvider = CaptureRuntimeProvider,
            instrumentationMode = WebViewInstrumentationMode.MANUAL,
        )
}

/** Stable JVM entry point for Capture Gradle plugin generated bytecode. */
internal object WebViewCaptureInternals {
    private const val BRIDGE_NAME = "BitdriftLogger"
    private const val TAG_KEY_INSTRUMENTED = 0x62697464 // "bitd" in hex, unique key for setTag

    @SuppressLint("SetJavaScriptEnabled", "RequiresFeature")
    @JvmStatic
    fun instrumentInternally(
        webview: WebView,
        logger: ILogger?,
        runtimeProvider: IRuntimeProvider,
        instrumentationMode: WebViewInstrumentationMode,
    ) {
        val effectiveLogger = logger ?: Capture.logger()

        val loggerImpl = effectiveLogger as? LoggerImpl
        if (loggerImpl == null) {
            Log.w(
                LOG_TAG,
                "WebView instrumentation skipped: SDK still not initialized. " +
                    "Call Capture.Logger.start() before instrumenting WebViews.",
            )
            return
        }

        if (!runtimeProvider.isRuntimeFeatureEnabled(RuntimeFeature.WEBVIEW_INSTRUMENTATION)) {
            return
        }

        @OptIn(ExperimentalBitdriftApi::class)
        val webViewConfig = loggerImpl.webViewConfiguration
        if (webViewConfig == null) {
            effectiveLogger.logInstrumentationNotInitialized("WebViewConfiguration not provided")
            return
        }

        if (webview.isAlreadyInstrumented()) {
            return
        }

        if (
            instrumentationMode == WebViewInstrumentationMode.AUTOMATIC_JAVASCRIPT_ENABLED_ONLY &&
            !webview.settings.javaScriptEnabled
        ) {
            effectiveLogger.logAutomaticInstrumentationSkipped()
            return
        }

        val notSupportedReason = getNotSupportedReason()
        if (notSupportedReason != null) {
            effectiveLogger.logInstrumentationNotInitialized(notSupportedReason)
            return
        }

        if (
            instrumentationMode != WebViewInstrumentationMode.AUTOMATIC_JAVASCRIPT_ENABLED_ONLY &&
            !webview.settings.javaScriptEnabled
        ) {
            webview.settings.javaScriptEnabled = true
        }

        val bridgeHandler = WebViewBridgeMessageHandler(loggerImpl, instrumentationMode.name)
        webview.addJavascriptInterface(bridgeHandler, BRIDGE_NAME)

        injectScript(webview, effectiveLogger, webViewConfig)

        webview.markAsInstrumented()
    }

    private fun isWebkitAvailable(): Boolean =
        runCatching {
            Class.forName("androidx.webkit.WebViewFeature")
        }.isSuccess

    private fun WebView.isAlreadyInstrumented(): Boolean = getTag(TAG_KEY_INSTRUMENTED) == true

    private fun WebView.markAsInstrumented() = setTag(TAG_KEY_INSTRUMENTED, true)

    private fun ILogger.logInstrumentationNotInitialized(reason: String) {
        log(
            LogLevel.WARNING,
            fieldsOf(
                "reason" to reason,
                "_source" to "webview",
            ),
        ) {
            "webview.notInitialized"
        }
    }

    private fun ILogger.logAutomaticInstrumentationSkipped() {
        log(
            LogLevel.WARNING,
            fieldsOf(
                "_instrumentation_mode" to WebViewInstrumentationMode.AUTOMATIC_JAVASCRIPT_ENABLED_ONLY.name,
                "_source" to "webview",
                "reason" to "JavaScript is not already enabled",
            ),
        ) {
            "webview.automaticInstrumentationSkipped"
        }
    }

    private fun getNotSupportedReason(): String? =
        when {
            !isWebkitAvailable() -> "androidx.webkit not available"
            !WebViewFeature.isFeatureSupported(WebViewFeature.DOCUMENT_START_SCRIPT) ->
                "WebViewFeature.DOCUMENT_START_SCRIPT not supported"

            !WebViewFeature.isFeatureSupported(WebViewFeature.GET_WEB_VIEW_CLIENT) ->
                "WebViewFeature.GET_WEB_VIEW_CLIENT not supported"

            else -> null
        }

    @SuppressLint("RequiresFeature")
    private fun injectScript(
        webview: WebView,
        logger: IInternalLogger?,
        config: WebViewConfiguration,
    ) {
        runCatching {
            val script = WebViewBridgeScript.getScript(config)
            WebViewCompat.addDocumentStartJavaScript(
                webview,
                script,
                setOf("*"), // Apply to all frames
            )
            logger?.logInternal(type = LogType.INTERNALSDK, LogLevel.DEBUG, ArrayFields.EMPTY) {
                "WebView bridge script injected successfully"
            }
        }.getOrElse { error ->
            logger?.log(LogLevel.WARNING, fieldsOf("_error" to (error.message ?: ""))) {
                "Failed to inject WebView bridge script"
            }
        }
    }
}

/** Describes how a specific WebView was instrumented for internal telemetry. */
internal enum class WebViewInstrumentationMode {
    AUTOMATIC_ALWAYS,
    AUTOMATIC_JAVASCRIPT_ENABLED_ONLY,
    MANUAL,
}
