load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "alloc",
    srcs = ["lib.rs"],
    crate_root = "lib.rs",
    edition = "2021",
    visibility = ["//visibility:public"],
    deps = [],
)
