// automatically generated by the FlatBuffers compiler, do not modify

package io.bitdrift.capture.reports.binformat.v1

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class AppBuildNumber : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : AppBuildNumber {
        __init(_i, _bb)
        return this
    }
    val versionCode : Long
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getLong(o + bb_pos) else 0L
        }
    val cfBundleVersion : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val cfBundleVersionAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun cfBundleVersionInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsAppBuildNumber(_bb: ByteBuffer): AppBuildNumber = getRootAsAppBuildNumber(_bb, AppBuildNumber())
        fun getRootAsAppBuildNumber(_bb: ByteBuffer, obj: AppBuildNumber): AppBuildNumber {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createAppBuildNumber(builder: FlatBufferBuilder, versionCode: Long, cfBundleVersionOffset: Int) : Int {
            builder.startTable(2)
            addVersionCode(builder, versionCode)
            addCfBundleVersion(builder, cfBundleVersionOffset)
            return endAppBuildNumber(builder)
        }
        fun startAppBuildNumber(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addVersionCode(builder: FlatBufferBuilder, versionCode: Long) = builder.addLong(0, versionCode, 0L)
        fun addCfBundleVersion(builder: FlatBufferBuilder, cfBundleVersion: Int) = builder.addOffset(1, cfBundleVersion, 0)
        fun endAppBuildNumber(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
