// automatically generated by the FlatBuffers compiler, do not modify

package io.bitdrift.capture.reports.binformat.v1

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class AppMetrics : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : AppMetrics {
        __init(_i, _bb)
        return this
    }
    val appId : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val appIdAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun appIdInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val memory : io.bitdrift.capture.reports.binformat.v1.Memory? get() = memory(io.bitdrift.capture.reports.binformat.v1.Memory())
    fun memory(obj: io.bitdrift.capture.reports.binformat.v1.Memory) : io.bitdrift.capture.reports.binformat.v1.Memory? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    val version : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val versionAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun versionInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    val buildNumber : io.bitdrift.capture.reports.binformat.v1.AppBuildNumber? get() = buildNumber(io.bitdrift.capture.reports.binformat.v1.AppBuildNumber())
    fun buildNumber(obj: io.bitdrift.capture.reports.binformat.v1.AppBuildNumber) : io.bitdrift.capture.reports.binformat.v1.AppBuildNumber? {
        val o = __offset(10)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsAppMetrics(_bb: ByteBuffer): AppMetrics = getRootAsAppMetrics(_bb, AppMetrics())
        fun getRootAsAppMetrics(_bb: ByteBuffer, obj: AppMetrics): AppMetrics {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun startAppMetrics(builder: FlatBufferBuilder) = builder.startTable(4)
        fun addAppId(builder: FlatBufferBuilder, appId: Int) = builder.addOffset(0, appId, 0)
        fun addMemory(builder: FlatBufferBuilder, memory: Int) = builder.addStruct(1, memory, 0)
        fun addVersion(builder: FlatBufferBuilder, version: Int) = builder.addOffset(2, version, 0)
        fun addBuildNumber(builder: FlatBufferBuilder, buildNumber: Int) = builder.addOffset(3, buildNumber, 0)
        fun endAppMetrics(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
