// automatically generated by the FlatBuffers compiler, do not modify

package io.bitdrift.capture.reports.binformat.v1

@Suppress("unused")
class Architecture private constructor() {
    companion object {
        const val Unknown: Byte = 0
        const val arm32: Byte = 1
        const val arm64: Byte = 2
        const val x86: Byte = 3
        const val x86_64: Byte = 4
    }
}
