// automatically generated by the FlatBuffers compiler, do not modify

package io.bitdrift.capture.reports.binformat.v1

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class DeviceMetrics : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : DeviceMetrics {
        __init(_i, _bb)
        return this
    }
    val time : io.bitdrift.capture.reports.binformat.v1.Timestamp? get() = time(io.bitdrift.capture.reports.binformat.v1.Timestamp())
    fun time(obj: io.bitdrift.capture.reports.binformat.v1.Timestamp) : io.bitdrift.capture.reports.binformat.v1.Timestamp? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    val timezone : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val timezoneAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun timezoneInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val powerMetrics : io.bitdrift.capture.reports.binformat.v1.PowerMetrics? get() = powerMetrics(io.bitdrift.capture.reports.binformat.v1.PowerMetrics())
    fun powerMetrics(obj: io.bitdrift.capture.reports.binformat.v1.PowerMetrics) : io.bitdrift.capture.reports.binformat.v1.PowerMetrics? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val networkState : Byte
        get() {
            val o = __offset(10)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    val rotation : Byte
        get() {
            val o = __offset(12)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    val arch : Byte
        get() {
            val o = __offset(14)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    val manufacturer : String?
        get() {
            val o = __offset(16)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val manufacturerAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(16, 1)
    fun manufacturerInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 16, 1)
    val model : String?
        get() {
            val o = __offset(18)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val modelAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(18, 1)
    fun modelInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 18, 1)
    val osBuild : io.bitdrift.capture.reports.binformat.v1.OSBuild? get() = osBuild(io.bitdrift.capture.reports.binformat.v1.OSBuild())
    fun osBuild(obj: io.bitdrift.capture.reports.binformat.v1.OSBuild) : io.bitdrift.capture.reports.binformat.v1.OSBuild? {
        val o = __offset(20)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val platform : Byte
        get() {
            val o = __offset(22)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    fun cpuAbis(j: Int) : String? {
        val o = __offset(24)
        return if (o != 0) {
            __string(__vector(o) + j * 4)
        } else {
            null
        }
    }
    val cpuAbisLength : Int
        get() {
            val o = __offset(24); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsDeviceMetrics(_bb: ByteBuffer): DeviceMetrics = getRootAsDeviceMetrics(_bb, DeviceMetrics())
        fun getRootAsDeviceMetrics(_bb: ByteBuffer, obj: DeviceMetrics): DeviceMetrics {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun startDeviceMetrics(builder: FlatBufferBuilder) = builder.startTable(11)
        fun addTime(builder: FlatBufferBuilder, time: Int) = builder.addStruct(0, time, 0)
        fun addTimezone(builder: FlatBufferBuilder, timezone: Int) = builder.addOffset(1, timezone, 0)
        fun addPowerMetrics(builder: FlatBufferBuilder, powerMetrics: Int) = builder.addOffset(2, powerMetrics, 0)
        fun addNetworkState(builder: FlatBufferBuilder, networkState: Byte) = builder.addByte(3, networkState, 0)
        fun addRotation(builder: FlatBufferBuilder, rotation: Byte) = builder.addByte(4, rotation, 0)
        fun addArch(builder: FlatBufferBuilder, arch: Byte) = builder.addByte(5, arch, 0)
        fun addManufacturer(builder: FlatBufferBuilder, manufacturer: Int) = builder.addOffset(6, manufacturer, 0)
        fun addModel(builder: FlatBufferBuilder, model: Int) = builder.addOffset(7, model, 0)
        fun addOsBuild(builder: FlatBufferBuilder, osBuild: Int) = builder.addOffset(8, osBuild, 0)
        fun addPlatform(builder: FlatBufferBuilder, platform: Byte) = builder.addByte(9, platform, 0)
        fun addCpuAbis(builder: FlatBufferBuilder, cpuAbis: Int) = builder.addOffset(10, cpuAbis, 0)
        fun createCpuAbisVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startCpuAbisVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endDeviceMetrics(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
