// automatically generated by the FlatBuffers compiler, do not modify

package io.bitdrift.capture.reports.binformat.v1

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class Error : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Error {
        __init(_i, _bb)
        return this
    }
    val name : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val nameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun nameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val reason : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val reasonAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun reasonInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    fun stackTrace(j: Int) : io.bitdrift.capture.reports.binformat.v1.Frame? = stackTrace(io.bitdrift.capture.reports.binformat.v1.Frame(), j)
    fun stackTrace(obj: io.bitdrift.capture.reports.binformat.v1.Frame, j: Int) : io.bitdrift.capture.reports.binformat.v1.Frame? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val stackTraceLength : Int
        get() {
            val o = __offset(8); return if (o != 0) __vector_len(o) else 0
        }
    val relationToNext : Byte
        get() {
            val o = __offset(10)
            return if(o != 0) bb.get(o + bb_pos) else 1
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsError(_bb: ByteBuffer): Error = getRootAsError(_bb, Error())
        fun getRootAsError(_bb: ByteBuffer, obj: Error): Error {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createError(builder: FlatBufferBuilder, nameOffset: Int, reasonOffset: Int, stackTraceOffset: Int, relationToNext: Byte) : Int {
            builder.startTable(4)
            addStackTrace(builder, stackTraceOffset)
            addReason(builder, reasonOffset)
            addName(builder, nameOffset)
            addRelationToNext(builder, relationToNext)
            return endError(builder)
        }
        fun startError(builder: FlatBufferBuilder) = builder.startTable(4)
        fun addName(builder: FlatBufferBuilder, name: Int) = builder.addOffset(0, name, 0)
        fun addReason(builder: FlatBufferBuilder, reason: Int) = builder.addOffset(1, reason, 0)
        fun addStackTrace(builder: FlatBufferBuilder, stackTrace: Int) = builder.addOffset(2, stackTrace, 0)
        fun createStackTraceVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startStackTraceVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addRelationToNext(builder: FlatBufferBuilder, relationToNext: Byte) = builder.addByte(3, relationToNext, 1)
        fun endError(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
