// automatically generated by the FlatBuffers compiler, do not modify

package io.bitdrift.capture.reports.binformat.v1

@Suppress("unused")
class ErrorRelation private constructor() {
    companion object {
        const val CausedBy: Byte = 1
    }
}
