// automatically generated by the FlatBuffers compiler, do not modify

package io.bitdrift.capture.reports.binformat.v1

@Suppress("unused")
class EventType private constructor() {
    companion object {
        const val Unknown: Byte = 0
        const val AppNotResponding: Byte = 1
        const val HandledError: Byte = 2
        const val JVMCrash: Byte = 3
        const val MemoryTermination: Byte = 4
        const val NativeCrash: Byte = 5
        const val StrictModeViolation: Byte = 6
    }
}
