// automatically generated by the FlatBuffers compiler, do not modify

package io.bitdrift.capture.reports.binformat.v1

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class Frame : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Frame {
        __init(_i, _bb)
        return this
    }
    val type : Byte
        get() {
            val o = __offset(4)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    val className : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val classNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun classNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val symbolName : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val symbolNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun symbolNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    val sourceFile : io.bitdrift.capture.reports.binformat.v1.SourceFile? get() = sourceFile(io.bitdrift.capture.reports.binformat.v1.SourceFile())
    fun sourceFile(obj: io.bitdrift.capture.reports.binformat.v1.SourceFile) : io.bitdrift.capture.reports.binformat.v1.SourceFile? {
        val o = __offset(10)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val imageId : String?
        get() {
            val o = __offset(12)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val imageIdAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(12, 1)
    fun imageIdInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 12, 1)
    val frameAddress : ULong
        get() {
            val o = __offset(14)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val symbolAddress : ULong
        get() {
            val o = __offset(16)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    fun state(j: Int) : String? {
        val o = __offset(18)
        return if (o != 0) {
            __string(__vector(o) + j * 4)
        } else {
            null
        }
    }
    val stateLength : Int
        get() {
            val o = __offset(18); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsFrame(_bb: ByteBuffer): Frame = getRootAsFrame(_bb, Frame())
        fun getRootAsFrame(_bb: ByteBuffer, obj: Frame): Frame {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createFrame(builder: FlatBufferBuilder, type: Byte, classNameOffset: Int, symbolNameOffset: Int, sourceFileOffset: Int, imageIdOffset: Int, frameAddress: ULong, symbolAddress: ULong, stateOffset: Int) : Int {
            builder.startTable(8)
            addSymbolAddress(builder, symbolAddress)
            addFrameAddress(builder, frameAddress)
            addState(builder, stateOffset)
            addImageId(builder, imageIdOffset)
            addSourceFile(builder, sourceFileOffset)
            addSymbolName(builder, symbolNameOffset)
            addClassName(builder, classNameOffset)
            addType(builder, type)
            return endFrame(builder)
        }
        fun startFrame(builder: FlatBufferBuilder) = builder.startTable(8)
        fun addType(builder: FlatBufferBuilder, type: Byte) = builder.addByte(0, type, 0)
        fun addClassName(builder: FlatBufferBuilder, className: Int) = builder.addOffset(1, className, 0)
        fun addSymbolName(builder: FlatBufferBuilder, symbolName: Int) = builder.addOffset(2, symbolName, 0)
        fun addSourceFile(builder: FlatBufferBuilder, sourceFile: Int) = builder.addOffset(3, sourceFile, 0)
        fun addImageId(builder: FlatBufferBuilder, imageId: Int) = builder.addOffset(4, imageId, 0)
        fun addFrameAddress(builder: FlatBufferBuilder, frameAddress: ULong) = builder.addLong(5, frameAddress.toLong(), 0)
        fun addSymbolAddress(builder: FlatBufferBuilder, symbolAddress: ULong) = builder.addLong(6, symbolAddress.toLong(), 0)
        fun addState(builder: FlatBufferBuilder, state: Int) = builder.addOffset(7, state, 0)
        fun createStateVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startStateVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endFrame(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
