// automatically generated by the FlatBuffers compiler, do not modify

package io.bitdrift.capture.reports.binformat.v1

@Suppress("unused")
class FrameType private constructor() {
    companion object {
        const val Unknown: Byte = 0
        const val JVM: Byte = 1
        const val DWARF: Byte = 2
        const val AndroidNative: Byte = 3
    }
}
