// automatically generated by the FlatBuffers compiler, do not modify

package io.bitdrift.capture.reports.binformat.v1

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class Memory : Struct() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Memory {
        __init(_i, _bb)
        return this
    }
    val total : ULong get() = bb.getLong(bb_pos + 0).toULong()
    val free : ULong get() = bb.getLong(bb_pos + 8).toULong()
    val used : ULong get() = bb.getLong(bb_pos + 16).toULong()
    companion object {
        fun createMemory(builder: FlatBufferBuilder, total: ULong, free: ULong, used: ULong) : Int {
            builder.prep(8, 24)
            builder.putLong(used.toLong())
            builder.putLong(free.toLong())
            builder.putLong(total.toLong())
            return builder.offset()
        }
    }
}
