// automatically generated by the FlatBuffers compiler, do not modify

package io.bitdrift.capture.reports.binformat.v1

@Suppress("unused")
class NetworkState private constructor() {
    companion object {
        const val Unknown: Byte = 0
        const val Disconnected: Byte = 1
        const val Cellular: Byte = 2
        const val WiFi: Byte = 3
    }
}
