// automatically generated by the FlatBuffers compiler, do not modify

package io.bitdrift.capture.reports.binformat.v1

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class OSBuild : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : OSBuild {
        __init(_i, _bb)
        return this
    }
    val version : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val versionAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun versionInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val brand : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val brandAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun brandInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val fingerprint : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val fingerprintAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun fingerprintInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    val kernOsversion : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val kernOsversionAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun kernOsversionInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsOSBuild(_bb: ByteBuffer): OSBuild = getRootAsOSBuild(_bb, OSBuild())
        fun getRootAsOSBuild(_bb: ByteBuffer, obj: OSBuild): OSBuild {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createOSBuild(builder: FlatBufferBuilder, versionOffset: Int, brandOffset: Int, fingerprintOffset: Int, kernOsversionOffset: Int) : Int {
            builder.startTable(4)
            addKernOsversion(builder, kernOsversionOffset)
            addFingerprint(builder, fingerprintOffset)
            addBrand(builder, brandOffset)
            addVersion(builder, versionOffset)
            return endOSBuild(builder)
        }
        fun startOSBuild(builder: FlatBufferBuilder) = builder.startTable(4)
        fun addVersion(builder: FlatBufferBuilder, version: Int) = builder.addOffset(0, version, 0)
        fun addBrand(builder: FlatBufferBuilder, brand: Int) = builder.addOffset(1, brand, 0)
        fun addFingerprint(builder: FlatBufferBuilder, fingerprint: Int) = builder.addOffset(2, fingerprint, 0)
        fun addKernOsversion(builder: FlatBufferBuilder, kernOsversion: Int) = builder.addOffset(3, kernOsversion, 0)
        fun endOSBuild(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
