// automatically generated by the FlatBuffers compiler, do not modify

package io.bitdrift.capture.reports.binformat.v1

@Suppress("unused")
class Platform private constructor() {
    companion object {
        const val Unknown: Byte = 0
        const val Android: Byte = 1
        const val iOS: Byte = 2
        const val macOS: Byte = 3
    }
}
