// automatically generated by the FlatBuffers compiler, do not modify

package io.bitdrift.capture.reports.binformat.v1

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class PowerMetrics : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : PowerMetrics {
        __init(_i, _bb)
        return this
    }
    val powerState : Byte
        get() {
            val o = __offset(4)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    val chargePercent : UByte
        get() {
            val o = __offset(6)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsPowerMetrics(_bb: ByteBuffer): PowerMetrics = getRootAsPowerMetrics(_bb, PowerMetrics())
        fun getRootAsPowerMetrics(_bb: ByteBuffer, obj: PowerMetrics): PowerMetrics {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createPowerMetrics(builder: FlatBufferBuilder, powerState: Byte, chargePercent: UByte) : Int {
            builder.startTable(2)
            addChargePercent(builder, chargePercent)
            addPowerState(builder, powerState)
            return endPowerMetrics(builder)
        }
        fun startPowerMetrics(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addPowerState(builder: FlatBufferBuilder, powerState: Byte) = builder.addByte(0, powerState, 0)
        fun addChargePercent(builder: FlatBufferBuilder, chargePercent: UByte) = builder.addByte(1, chargePercent.toByte(), 0)
        fun endPowerMetrics(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
