// automatically generated by the FlatBuffers compiler, do not modify

package io.bitdrift.capture.reports.binformat.v1

@Suppress("unused")
class PowerState private constructor() {
    companion object {
        const val Unknown: Byte = 0
        const val RunningOnBattery: Byte = 1
        const val PluggedInNoBattery: Byte = 2
        const val PluggedInCharging: Byte = 3
        const val PluggedInCharged: Byte = 4
    }
}
