// automatically generated by the FlatBuffers compiler, do not modify

package io.bitdrift.capture.reports.binformat.v1

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class Report : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Report {
        __init(_i, _bb)
        return this
    }
    val sdk : io.bitdrift.capture.reports.binformat.v1.SDKInfo? get() = sdk(io.bitdrift.capture.reports.binformat.v1.SDKInfo())
    fun sdk(obj: io.bitdrift.capture.reports.binformat.v1.SDKInfo) : io.bitdrift.capture.reports.binformat.v1.SDKInfo? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val appMetrics : io.bitdrift.capture.reports.binformat.v1.AppMetrics? get() = appMetrics(io.bitdrift.capture.reports.binformat.v1.AppMetrics())
    fun appMetrics(obj: io.bitdrift.capture.reports.binformat.v1.AppMetrics) : io.bitdrift.capture.reports.binformat.v1.AppMetrics? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val deviceMetrics : io.bitdrift.capture.reports.binformat.v1.DeviceMetrics? get() = deviceMetrics(io.bitdrift.capture.reports.binformat.v1.DeviceMetrics())
    fun deviceMetrics(obj: io.bitdrift.capture.reports.binformat.v1.DeviceMetrics) : io.bitdrift.capture.reports.binformat.v1.DeviceMetrics? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    fun errors(j: Int) : io.bitdrift.capture.reports.binformat.v1.Error? = errors(io.bitdrift.capture.reports.binformat.v1.Error(), j)
    fun errors(obj: io.bitdrift.capture.reports.binformat.v1.Error, j: Int) : io.bitdrift.capture.reports.binformat.v1.Error? {
        val o = __offset(10)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val errorsLength : Int
        get() {
            val o = __offset(10); return if (o != 0) __vector_len(o) else 0
        }
    val threads : io.bitdrift.capture.reports.binformat.v1.Threads? get() = threads(io.bitdrift.capture.reports.binformat.v1.Threads())
    fun threads(obj: io.bitdrift.capture.reports.binformat.v1.Threads) : io.bitdrift.capture.reports.binformat.v1.Threads? {
        val o = __offset(12)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    fun binaryImages(j: Int) : io.bitdrift.capture.reports.binformat.v1.BinaryImage? = binaryImages(io.bitdrift.capture.reports.binformat.v1.BinaryImage(), j)
    fun binaryImages(obj: io.bitdrift.capture.reports.binformat.v1.BinaryImage, j: Int) : io.bitdrift.capture.reports.binformat.v1.BinaryImage? {
        val o = __offset(14)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val binaryImagesLength : Int
        get() {
            val o = __offset(14); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsReport(_bb: ByteBuffer): Report = getRootAsReport(_bb, Report())
        fun getRootAsReport(_bb: ByteBuffer, obj: Report): Report {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createReport(builder: FlatBufferBuilder, sdkOffset: Int, appMetricsOffset: Int, deviceMetricsOffset: Int, errorsOffset: Int, threadsOffset: Int, binaryImagesOffset: Int) : Int {
            builder.startTable(6)
            addBinaryImages(builder, binaryImagesOffset)
            addThreads(builder, threadsOffset)
            addErrors(builder, errorsOffset)
            addDeviceMetrics(builder, deviceMetricsOffset)
            addAppMetrics(builder, appMetricsOffset)
            addSdk(builder, sdkOffset)
            return endReport(builder)
        }
        fun startReport(builder: FlatBufferBuilder) = builder.startTable(6)
        fun addSdk(builder: FlatBufferBuilder, sdk: Int) = builder.addOffset(0, sdk, 0)
        fun addAppMetrics(builder: FlatBufferBuilder, appMetrics: Int) = builder.addOffset(1, appMetrics, 0)
        fun addDeviceMetrics(builder: FlatBufferBuilder, deviceMetrics: Int) = builder.addOffset(2, deviceMetrics, 0)
        fun addErrors(builder: FlatBufferBuilder, errors: Int) = builder.addOffset(3, errors, 0)
        fun createErrorsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startErrorsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addThreads(builder: FlatBufferBuilder, threads: Int) = builder.addOffset(4, threads, 0)
        fun addBinaryImages(builder: FlatBufferBuilder, binaryImages: Int) = builder.addOffset(5, binaryImages, 0)
        fun createBinaryImagesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startBinaryImagesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endReport(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
        fun finishReportBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finish(offset)
        fun finishSizePrefixedReportBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finishSizePrefixed(offset)
    }
}
