// automatically generated by the FlatBuffers compiler, do not modify

package io.bitdrift.capture.reports.binformat.v1

@Suppress("unused")
class Rotation private constructor() {
    companion object {
        const val Unknown: Byte = 0
        const val Portrait: Byte = 1
        const val LandscapeRight: Byte = 2
        const val LandscapeLeft: Byte = 3
        const val PortraitUpsideDown: Byte = 4
    }
}
