// automatically generated by the FlatBuffers compiler, do not modify

package io.bitdrift.capture.reports.binformat.v1

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class SourceFile : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : SourceFile {
        __init(_i, _bb)
        return this
    }
    val path : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val pathAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun pathInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val line : Long
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getLong(o + bb_pos) else 0L
        }
    val column : Long
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getLong(o + bb_pos) else 0L
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsSourceFile(_bb: ByteBuffer): SourceFile = getRootAsSourceFile(_bb, SourceFile())
        fun getRootAsSourceFile(_bb: ByteBuffer, obj: SourceFile): SourceFile {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createSourceFile(builder: FlatBufferBuilder, pathOffset: Int, line: Long, column: Long) : Int {
            builder.startTable(3)
            addColumn(builder, column)
            addLine(builder, line)
            addPath(builder, pathOffset)
            return endSourceFile(builder)
        }
        fun startSourceFile(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addPath(builder: FlatBufferBuilder, path: Int) = builder.addOffset(0, path, 0)
        fun addLine(builder: FlatBufferBuilder, line: Long) = builder.addLong(1, line, 0L)
        fun addColumn(builder: FlatBufferBuilder, column: Long) = builder.addLong(2, column, 0L)
        fun endSourceFile(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
