// automatically generated by the FlatBuffers compiler, do not modify

package io.bitdrift.capture.reports.binformat.v1

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class Threads : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Threads {
        __init(_i, _bb)
        return this
    }
    val count : UShort
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getShort(o + bb_pos).toUShort() else 0u
        }
    fun threads(j: Int) : io.bitdrift.capture.reports.binformat.v1.Thread? = threads(io.bitdrift.capture.reports.binformat.v1.Thread(), j)
    fun threads(obj: io.bitdrift.capture.reports.binformat.v1.Thread, j: Int) : io.bitdrift.capture.reports.binformat.v1.Thread? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val threadsLength : Int
        get() {
            val o = __offset(6); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsThreads(_bb: ByteBuffer): Threads = getRootAsThreads(_bb, Threads())
        fun getRootAsThreads(_bb: ByteBuffer, obj: Threads): Threads {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createThreads(builder: FlatBufferBuilder, count: UShort, threadsOffset: Int) : Int {
            builder.startTable(2)
            addThreads(builder, threadsOffset)
            addCount(builder, count)
            return endThreads(builder)
        }
        fun startThreads(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addCount(builder: FlatBufferBuilder, count: UShort) = builder.addShort(0, count.toShort(), 0)
        fun addThreads(builder: FlatBufferBuilder, threads: Int) = builder.addOffset(1, threads, 0)
        fun createThreadsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startThreadsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endThreads(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
