// automatically generated by the FlatBuffers compiler, do not modify

package io.bitdrift.capture.reports.binformat.v1

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class Thread : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Thread {
        __init(_i, _bb)
        return this
    }
    val name : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val nameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun nameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val active : Boolean
        get() {
            val o = __offset(6)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val index : UInt
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val state : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val stateAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun stateInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    val priority : Float
        get() {
            val o = __offset(12)
            return if(o != 0) bb.getFloat(o + bb_pos) else 0.0f
        }
    val qualityOfService : Byte
        get() {
            val o = __offset(14)
            return if(o != 0) bb.get(o + bb_pos) else -1
        }
    fun stackTrace(j: Int) : io.bitdrift.capture.reports.binformat.v1.Frame? = stackTrace(io.bitdrift.capture.reports.binformat.v1.Frame(), j)
    fun stackTrace(obj: io.bitdrift.capture.reports.binformat.v1.Frame, j: Int) : io.bitdrift.capture.reports.binformat.v1.Frame? {
        val o = __offset(16)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val stackTraceLength : Int
        get() {
            val o = __offset(16); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsThread(_bb: ByteBuffer): Thread = getRootAsThread(_bb, Thread())
        fun getRootAsThread(_bb: ByteBuffer, obj: Thread): Thread {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createThread(builder: FlatBufferBuilder, nameOffset: Int, active: Boolean, index: UInt, stateOffset: Int, priority: Float, qualityOfService: Byte, stackTraceOffset: Int) : Int {
            builder.startTable(7)
            addStackTrace(builder, stackTraceOffset)
            addPriority(builder, priority)
            addState(builder, stateOffset)
            addIndex(builder, index)
            addName(builder, nameOffset)
            addQualityOfService(builder, qualityOfService)
            addActive(builder, active)
            return endThread(builder)
        }
        fun startThread(builder: FlatBufferBuilder) = builder.startTable(7)
        fun addName(builder: FlatBufferBuilder, name: Int) = builder.addOffset(0, name, 0)
        fun addActive(builder: FlatBufferBuilder, active: Boolean) = builder.addBoolean(1, active, false)
        fun addIndex(builder: FlatBufferBuilder, index: UInt) = builder.addInt(2, index.toInt(), 0)
        fun addState(builder: FlatBufferBuilder, state: Int) = builder.addOffset(3, state, 0)
        fun addPriority(builder: FlatBufferBuilder, priority: Float) = builder.addFloat(4, priority, 0.0)
        fun addQualityOfService(builder: FlatBufferBuilder, qualityOfService: Byte) = builder.addByte(5, qualityOfService, -1)
        fun addStackTrace(builder: FlatBufferBuilder, stackTrace: Int) = builder.addOffset(6, stackTrace, 0)
        fun createStackTraceVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startStackTraceVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endThread(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
