// automatically generated by the FlatBuffers compiler, do not modify

package io.bitdrift.capture.reports.binformat.v1

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class Timestamp : Struct() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Timestamp {
        __init(_i, _bb)
        return this
    }
    val seconds : ULong get() = bb.getLong(bb_pos + 0).toULong()
    val nanos : UInt get() = bb.getInt(bb_pos + 8).toUInt()
    companion object {
        fun createTimestamp(builder: FlatBufferBuilder, seconds: ULong, nanos: UInt) : Int {
            builder.prep(8, 16)
            builder.pad(4)
            builder.putInt(nanos.toInt())
            builder.putLong(seconds.toLong())
            return builder.offset()
        }
    }
}
