// automatically generated by the FlatBuffers compiler, do not modify
// ignore_for_file: unused_import, unused_field, unused_element, unused_local_variable, constant_identifier_names

library bitdrift_public.fbs.common.v1;

import 'dart:typed_data' show Uint8List;
import 'package:flat_buffers/flat_buffers.dart' as fb;

enum DataTypeId {
  NONE(0),
  string_data(1),
  binary_data(2);

  final int value;
  const DataTypeId(this.value);

  factory DataTypeId.fromValue(int value) {
    switch (value) {
      case 0:
        return DataTypeId.NONE;
      case 1:
        return DataTypeId.string_data;
      case 2:
        return DataTypeId.binary_data;
      default:
        throw StateError('Invalid value $value for bit flag enum');
    }
  }

  static DataTypeId? _createOrNull(int? value) =>
      value == null ? null : DataTypeId.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 2;
  static const fb.Reader<DataTypeId> reader = _DataTypeIdReader();
}

class _DataTypeIdReader extends fb.Reader<DataTypeId> {
  const _DataTypeIdReader();

  @override
  int get size => 1;

  @override
  DataTypeId read(fb.BufferContext bc, int offset) =>
      DataTypeId.fromValue(const fb.Uint8Reader().read(bc, offset));
}

class StringData {
  StringData._(this._bc, this._bcOffset);
  factory StringData(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<StringData> reader = _StringDataReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get data =>
      const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'StringData{data: ${data}}';
  }
}

class _StringDataReader extends fb.TableReader<StringData> {
  const _StringDataReader();

  @override
  StringData createObject(fb.BufferContext bc, int offset) =>
      StringData._(bc, offset);
}

class StringDataBuilder {
  StringDataBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addDataOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class StringDataObjectBuilder extends fb.ObjectBuilder {
  final String? _data;

  StringDataObjectBuilder({String? data}) : _data = data;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? dataOffset = _data == null
        ? null
        : fbBuilder.writeString(_data!);
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, dataOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class BinaryData {
  BinaryData._(this._bc, this._bcOffset);
  factory BinaryData(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<BinaryData> reader = _BinaryDataReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get dataType =>
      const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  List<int>? get data =>
      const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 6);

  @override
  String toString() {
    return 'BinaryData{dataType: ${dataType}, data: ${data}}';
  }
}

class _BinaryDataReader extends fb.TableReader<BinaryData> {
  const _BinaryDataReader();

  @override
  BinaryData createObject(fb.BufferContext bc, int offset) =>
      BinaryData._(bc, offset);
}

class BinaryDataBuilder {
  BinaryDataBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addDataTypeOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int addDataOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class BinaryDataObjectBuilder extends fb.ObjectBuilder {
  final String? _dataType;
  final List<int>? _data;

  BinaryDataObjectBuilder({String? dataType, List<int>? data})
    : _dataType = dataType,
      _data = data;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? dataTypeOffset = _dataType == null
        ? null
        : fbBuilder.writeString(_dataType!);
    final int? dataOffset = _data == null
        ? null
        : fbBuilder.writeListUint8(_data!);
    fbBuilder.startTable(2);
    fbBuilder.addOffset(0, dataTypeOffset);
    fbBuilder.addOffset(1, dataOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class Field {
  Field._(this._bc, this._bcOffset);
  factory Field(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Field> reader = _FieldReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get key =>
      const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  DataTypeId? get valueType => DataTypeId._createOrNull(
    const fb.Uint8Reader().vTableGetNullable(_bc, _bcOffset, 6),
  );
  dynamic get value {
    switch (valueType?.value) {
      case 1:
        return StringData.reader.vTableGetNullable(_bc, _bcOffset, 8);
      case 2:
        return BinaryData.reader.vTableGetNullable(_bc, _bcOffset, 8);
      default:
        return null;
    }
  }

  @override
  String toString() {
    return 'Field{key: ${key}, valueType: ${valueType}, value: ${value}}';
  }
}

class _FieldReader extends fb.TableReader<Field> {
  const _FieldReader();

  @override
  Field createObject(fb.BufferContext bc, int offset) => Field._(bc, offset);
}

class FieldBuilder {
  FieldBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(3);
  }

  int addKeyOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int addValueType(DataTypeId? valueType) {
    fbBuilder.addUint8(1, valueType?.value);
    return fbBuilder.offset;
  }

  int addValueOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class FieldObjectBuilder extends fb.ObjectBuilder {
  final String? _key;
  final DataTypeId? _valueType;
  final dynamic _value;

  FieldObjectBuilder({String? key, DataTypeId? valueType, dynamic value})
    : _key = key,
      _valueType = valueType,
      _value = value;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? keyOffset = _key == null ? null : fbBuilder.writeString(_key!);
    final int? valueOffset = _value?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(3);
    fbBuilder.addOffset(0, keyOffset);
    fbBuilder.addUint8(1, _valueType?.value);
    fbBuilder.addOffset(2, valueOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class Timestamp {
  Timestamp._(this._bc, this._bcOffset);
  factory Timestamp(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Timestamp> reader = _TimestampReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get seconds => const fb.Int64Reader().vTableGet(_bc, _bcOffset, 4, 0);
  int get nanos => const fb.Int32Reader().vTableGet(_bc, _bcOffset, 6, 0);

  @override
  String toString() {
    return 'Timestamp{seconds: ${seconds}, nanos: ${nanos}}';
  }
}

class _TimestampReader extends fb.TableReader<Timestamp> {
  const _TimestampReader();

  @override
  Timestamp createObject(fb.BufferContext bc, int offset) =>
      Timestamp._(bc, offset);
}

class TimestampBuilder {
  TimestampBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addSeconds(int? seconds) {
    fbBuilder.addInt64(0, seconds);
    return fbBuilder.offset;
  }

  int addNanos(int? nanos) {
    fbBuilder.addInt32(1, nanos);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class TimestampObjectBuilder extends fb.ObjectBuilder {
  final int? _seconds;
  final int? _nanos;

  TimestampObjectBuilder({int? seconds, int? nanos})
    : _seconds = seconds,
      _nanos = nanos;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.startTable(2);
    fbBuilder.addInt64(0, _seconds);
    fbBuilder.addInt32(1, _nanos);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
