import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Paths relative to the monorepo root
const repoRoot = path.join(__dirname, '../../..');
const bundlePath = path.join(__dirname, '../dist/bitdrift-webview.js');

// Output directly to SDK source directories
const kotlinOutputPath = path.join(
    repoRoot,
    'platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/webview/WebViewBridgeScript.kt',
);
const swiftOutputPath = path.join(repoRoot, 'platform/swift/source/integrations/webview/WebViewBridgeScript.swift');

// Read the bundled JavaScript
let bundleContent: string;
try {
    bundleContent = fs.readFileSync(bundlePath, 'utf8');
} catch (_error) {
    console.error('Bundle not found. Run "npm run build" first.');
    process.exit(1);
}

// Escape for Kotlin raw string (triple quotes)
const escapeForKotlin = (content: string): string => {
    // In Kotlin raw strings, we need to escape $ as ${'$'}
    // In JS replace(), $$ represents a literal $, so we use $${'$$'} to produce ${'$'}
    return content.replace(/\$/g, "$${'$$'}");
};

// Escape for Swift raw string
const escapeForSwift = (content: string): string => {
    // In Swift multi-line strings with #, we need to escape \# and interpolation
    // Using extended delimiters (#"..."#) so standard escapes don't apply
    return content.replace(/#/g, '\\#');
};

// Generate Kotlin file
const kotlinContent = `// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by: npm run generate
// Source: platform/webview/src/

package io.bitdrift.capture.webview

/**
 * Contains the bundled JavaScript SDK for WebView instrumentation.
 * This script is injected into WebViews to capture performance metrics,
 * network events, and user interactions.
 */
internal object WebViewBridgeScript {
    /**
     * The minified JavaScript bundle to inject into WebViews.
     */
    const val SCRIPT: String = """
${escapeForKotlin(bundleContent)}
"""
}
`;

// Generate Swift file
const swiftContent = `// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by: npm run generate
// Source: platform/webview/src/

import Foundation

/// Contains the bundled JavaScript SDK for WebView instrumentation.
/// This script is injected into WebViews to capture performance metrics,
/// network events, and user interactions.
enum WebViewBridgeScript {
    /// The minified JavaScript bundle to inject into WebViews.
    static let script: String = #"""
${escapeForSwift(bundleContent)}
"""#
}
`;

// Write files
fs.writeFileSync(kotlinOutputPath, kotlinContent);
fs.writeFileSync(swiftOutputPath, swiftContent);

console.log('Generated native files:');
console.log(`  - ${kotlinOutputPath}`);
console.log(`  - ${swiftOutputPath}`);
console.log(`Bundle size: ${(bundleContent.length / 1024).toFixed(2)} KB`);
