import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Paths relative to the monorepo root
const repoRoot = path.join(__dirname, '../../..');
const bundlePath = path.join(__dirname, '../dist/bitdrift-webview.js');

// Output directly to SDK source directories
const kotlinOutputPath = path.join(
    repoRoot,
    'platform/jvm/capture/src/main/kotlin/io/bitdrift/capture/webview/WebViewBridgeScript.kt',
);

// Read the bundled JavaScript
let bundleContent: string;
try {
    bundleContent = fs.readFileSync(bundlePath, 'utf8');
} catch (_error) {
    console.error('Bundle not found. Run "npm run build" first.');
    process.exit(1);
}

// The magic comment placeholder that will be replaced with config JSON at runtime
const CONFIG_PLACEHOLDER = '/* @magic __BITDRIFT_WEBVIEW_CONFIG_PLACEHOLDER__ */';

// Escape for Kotlin raw string (triple quotes)
const escapeForKotlin = (content: string): string => {
    // In Kotlin raw strings, we need to escape $ as ${'$'}
    // In JS replace(), $$ represents a literal $, so we use $${'$$'} to produce ${'$'}
    return content.replace(/\$/g, "$${'$$'}");
};

// License header for generated files
const licenseHeader = `// capture-sdk - bitdrift's client SDK
// Copyright Bitdrift, Inc. All rights reserved.
//
// Use of this source code is governed by a source available license that can be found in the
// LICENSE file or at:
// https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt

`;

// Verify the placeholder exists in the bundle
if (!bundleContent.includes(CONFIG_PLACEHOLDER)) {
    console.error(`Error: Bundle does not contain expected placeholder: ${CONFIG_PLACEHOLDER}`);
    console.error('Make sure the build script preserves magic comments.');
    process.exit(1);
}

// Split the bundle at the placeholder for Kotlin string concatenation
const placeholderIndex = bundleContent.indexOf(CONFIG_PLACEHOLDER);
const beforePlaceholder = bundleContent.substring(0, placeholderIndex);
const afterPlaceholder = bundleContent.substring(placeholderIndex + CONFIG_PLACEHOLDER.length);

// Generate Kotlin file
const kotlinContent = `${licenseHeader}// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by: npm run generate
// Source: platform/webview/src/

@file:Suppress("MaxLineLength")

package io.bitdrift.capture.webview

import org.json.JSONObject

/**
 * Contains the bundled JavaScript SDK for WebView instrumentation.
 * This script is injected into WebViews to capture performance metrics,
 * network events, and user interactions.
 */
internal object WebViewBridgeScript {
    private const val SCRIPT_PREFIX: String = """
${escapeForKotlin(beforePlaceholder)}"""

    private const val SCRIPT_SUFFIX: String = """${escapeForKotlin(afterPlaceholder)}
"""

    /**
     * Generates the JavaScript bundle with the provided configuration.
     *
     * @param config The WebView instrumentation configuration
     * @return The complete JavaScript bundle with config injected
     */
    fun getScript(config: WebViewConfiguration): String = SCRIPT_PREFIX + config.toJson() + SCRIPT_SUFFIX
}
`;

// Write files
fs.writeFileSync(kotlinOutputPath, kotlinContent);

console.log('Generated native files:');
console.log(`  - ${kotlinOutputPath}`);
console.log(`Bundle size: ${(bundleContent.length / 1024).toFixed(2)} KB`);
