// capture-sdk - bitdrift's client SDK
// Copyright Bitdrift, Inc. All rights reserved.
//
// Use of this source code is governed by a source available license that can be found in the
// LICENSE file or at:
// https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt

package io.bitdrift.capture

/**
 * THIS IS A STUB FILE. It makes the gradle build work, while the actual file
 * is generated by bazel based on the contents of platform/shared/.sdk_version
 */
object BuildConstants {
    /** Compiled version of the SDK (actual value generated during build) */
    const val SDK_VERSION = "x.x.x"
}
