# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bitdrift_public/protobuf/ingest/v1/api.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'bitdrift_public/protobuf/ingest/v1/api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from protos.validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,bitdrift_public/protobuf/ingest/v1/api.proto\x12\"bitdrift_public.protobuf.ingest.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"\xa3\x02\n\x13IngestMetricRequest\x12\x1a\n\tmetric_id\x18\x01 \x01(\tB\x07\xfa\x42\x04r\x02\x10\x01\x12W\n\rplatform_type\x18\x02 \x01(\x0e\x32\x36.bitdrift_public.protobuf.ingest.v1.MetricPlatformTypeB\x08\xfa\x42\x05\x82\x01\x02\x10\x01\x12\x17\n\x06\x61pp_id\x18\x03 \x01(\tB\x07\xfa\x42\x04r\x02\x10\x01\x12\x1c\n\x0b\x61pp_version\x18\x04 \x01(\tB\x07\xfa\x42\x04r\x02\x10\x01\x12-\n\ttimestamp\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x17\n\rcounter_delta\x18\x06 \x01(\x04H\x00\x42\x18\n\x11metric_value_type\x12\x03\xf8\x42\x01\"\x16\n\x14IngestMetricResponse*K\n\x12MetricPlatformType\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\t\n\x05\x41PPLE\x10\x01\x12\x0b\n\x07\x41NDROID\x10\x02\x12\x0c\n\x08\x45LECTRON\x10\x03\x32\x95\x01\n\rIngestService\x12\x83\x01\n\x0cIngestMetric\x12\x37.bitdrift_public.protobuf.ingest.v1.IngestMetricRequest\x1a\x38.bitdrift_public.protobuf.ingest.v1.IngestMetricResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bitdrift_public.protobuf.ingest.v1.api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INGESTMETRICREQUEST'].oneofs_by_name['metric_value_type']._loaded_options = None
  _globals['_INGESTMETRICREQUEST'].oneofs_by_name['metric_value_type']._serialized_options = b'\370B\001'
  _globals['_INGESTMETRICREQUEST'].fields_by_name['metric_id']._loaded_options = None
  _globals['_INGESTMETRICREQUEST'].fields_by_name['metric_id']._serialized_options = b'\372B\004r\002\020\001'
  _globals['_INGESTMETRICREQUEST'].fields_by_name['platform_type']._loaded_options = None
  _globals['_INGESTMETRICREQUEST'].fields_by_name['platform_type']._serialized_options = b'\372B\005\202\001\002\020\001'
  _globals['_INGESTMETRICREQUEST'].fields_by_name['app_id']._loaded_options = None
  _globals['_INGESTMETRICREQUEST'].fields_by_name['app_id']._serialized_options = b'\372B\004r\002\020\001'
  _globals['_INGESTMETRICREQUEST'].fields_by_name['app_version']._loaded_options = None
  _globals['_INGESTMETRICREQUEST'].fields_by_name['app_version']._serialized_options = b'\372B\004r\002\020\001'
  _globals['_METRICPLATFORMTYPE']._serialized_start=460
  _globals['_METRICPLATFORMTYPE']._serialized_end=535
  _globals['_INGESTMETRICREQUEST']._serialized_start=143
  _globals['_INGESTMETRICREQUEST']._serialized_end=434
  _globals['_INGESTMETRICRESPONSE']._serialized_start=436
  _globals['_INGESTMETRICRESPONSE']._serialized_end=458
  _globals['_INGESTSERVICE']._serialized_start=538
  _globals['_INGESTSERVICE']._serialized_end=687
# @@protoc_insertion_point(module_scope)
