name: Common Android SDK/NDK setup
description: Sets up Android SDK cmdline-tools, NDK, JDK, Rust toolchain, and emulator prerequisites

inputs:
  ndk-version:
    description: Android NDK version to install
    required: false
    default: "27.2.12479018"
  java-version:
    description: JDK version to install
    required: false
    default: "17"
  setup-emulator:
    description: Whether to set up emulator prerequisites (KVM, licenses)
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Set ANDROID_HOME and unset deprecated variable
      shell: bash
      run: |
        echo "ANDROID_HOME=${{ github.workspace }}/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=${{ github.workspace }}/android-sdk" >> $GITHUB_ENV

    - name: Install cmake and ninja
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y cmake ninja-build

    - name: Enable KVM group perms
      if: inputs.setup-emulator == 'true'
      shell: bash
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    - name: Set up JDK
      if: inputs.setup-emulator == 'true'
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: ${{ inputs.java-version }}
        cache: gradle

    - name: Set up Rust toolchain
      if: inputs.setup-emulator == 'true'
      uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b
      with:
        toolchain: stable
        targets: x86_64-unknown-linux-gnu,x86_64-linux-android,aarch64-linux-android
        components: rust-src

    - name: Cache Android NDK
      id: ndk-cache
      uses: actions/cache@v4
      with:
        path: ${{ env.ANDROID_HOME }}/ndk/${{ inputs.ndk-version }}
        key: ${{ runner.os }}-android-ndk-${{ inputs.ndk-version }}

    - name: Cache Android cmdline-tools
      id: cmdline-tools-cache
      uses: actions/cache@v4
      with:
        path: ${{ env.ANDROID_HOME }}/cmdline-tools/latest
        key: ${{ runner.os }}-android-cmdline-tools-v1

    - name: Verify cmdline-tools
      if: steps.cmdline-tools-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "cmdline-tools not found or incomplete. Installing..."
        mkdir -p $ANDROID_HOME/cmdline-tools
        cd $ANDROID_HOME/cmdline-tools
        curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -o cmdline-tools.zip
        unzip -q cmdline-tools.zip
        mv cmdline-tools latest

    - name: Install Android NDK
      if: steps.ndk-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
        echo "y" | sdkmanager --sdk_root=$ANDROID_HOME "ndk;${{ inputs.ndk-version }}"

    - name: Set ANDROID_NDK_HOME
      shell: bash
      run: echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/${{ inputs.ndk-version }}" >> $GITHUB_ENV

    - name: Set ANDROID_NDK_ROOT for aws-lc-sys
      shell: bash
      run: echo "ANDROID_NDK_ROOT=$ANDROID_HOME/ndk/${{ inputs.ndk-version }}" >> $GITHUB_ENV

    - name: Set CMAKE_TOOLCHAIN_FILE for Android NDK
      shell: bash
      run: echo "CMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk/${{ inputs.ndk-version }}/build/cmake/android.toolchain.cmake" >> $GITHUB_ENV

    - name: Accept Android SDK licenses
      if: inputs.setup-emulator == 'true'
      shell: bash
      run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

    - name: Touch local.properties
      shell: bash
      run: touch platform/jvm/local.properties

    - name: Cache cargo-ndk
      id: cargo-ndk-cache
      uses: actions/cache@v4
      with:
        path: ~/.cargo/bin/cargo-ndk
        key: ${{ runner.os }}-cargo-ndk-3.4

    - name: Install cargo-ndk
      if: steps.cargo-ndk-cache.outputs.cache-hit != 'true'
      shell: bash
      run: cargo install cargo-ndk --version 3.4.0 --locked
