name: Common Android SDK/NDK setup
description: Sets up Android SDK cmdline-tools and installs the NDK

inputs:
  ndk-version:
    description: Android NDK version to install
    required: false
    default: "27.2.12479018"

runs:
  using: "composite"
  steps:
    - name: Set ANDROID_HOME and unset deprecated variable
      shell: bash
      run: |
        echo "ANDROID_HOME=${{ github.workspace }}/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=${{ github.workspace }}/android-sdk" >> $GITHUB_ENV

    - name: Cache Android NDK
      id: ndk-cache
      uses: actions/cache@v4
      with:
        path: ${{ env.ANDROID_HOME }}/ndk/${{ inputs.ndk-version }}
        key: ${{ runner.os }}-android-ndk-${{ inputs.ndk-version }}

    - name: Cache Android cmdline-tools
      id: cmdline-tools-cache
      uses: actions/cache@v4
      with:
        path: ${{ env.ANDROID_HOME }}/cmdline-tools/latest
        key: ${{ runner.os }}-android-cmdline-tools-v1

    - name: Verify cmdline-tools
      if: steps.cmdline-tools-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "cmdline-tools not found or incomplete. Installing..."
        mkdir -p $ANDROID_HOME/cmdline-tools
        cd $ANDROID_HOME/cmdline-tools
        curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -o cmdline-tools.zip
        unzip -q cmdline-tools.zip
        mv cmdline-tools latest

    - name: Install Android NDK
      if: steps.ndk-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
        echo "y" | sdkmanager --sdk_root=$ANDROID_HOME "ndk;${{ inputs.ndk-version }}"

    - name: Touch local.properties
      shell: bash
      run: touch platform/jvm/local.properties

    - name: Cache cargo-ndk
      id: cargo-ndk-cache
      uses: actions/cache@v4
      with:
        path: ~/.cargo/bin/cargo-ndk
        key: ${{ runner.os }}-cargo-ndk-3.4
    - name: Install cargo-ndk
      if: steps.cargo-ndk-cache.outputs.cache-hit != 'true'
      shell: bash
      run: cargo install cargo-ndk --version 3.4.0 --locked
