load("//bazel:bitdrift_build_system.bzl", "bitdrift_rust_library")

bitdrift_rust_library(
    name = "bd_crash_reporter",
    tags = [
        "macos_only",
    ],
    visibility = ["//visibility:public"],
)
