#!/bin/sh

set -eu

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <rust version>" >&2
  exit 1
fi

VERSION="$1"
SCRIPT_DIR=$(
  CDPATH=
  cd -- "$(dirname -- "$0")"
  pwd
)
MODULE_FILE="$SCRIPT_DIR/../MODULE.bazel"
CHECKSUMS_FILE=$(mktemp "${TMPDIR:-/tmp}/rust-std-checksums.XXXXXX")
MODULE_FILE_TMP=$(mktemp "${TMPDIR:-/tmp}/capture-sdk-module.XXXXXX")

cleanup() {
  rm -f "$CHECKSUMS_FILE" "$MODULE_FILE_TMP"
}
trap cleanup EXIT HUP INT TERM

fetch_checksum() {
  archive="$1"
  checksum=$(curl --fail --location --silent --show-error "$archive.sha256" | awk '{ print $1 }')

  if [ "${#checksum}" -ne 64 ]; then
    echo "Missing or invalid checksum for $archive" >&2
    exit 1
  fi

  case "$checksum" in
    *[!0123456789abcdef]*)
      echo "Invalid SHA-256 checksum for $archive: $checksum" >&2
      exit 1
      ;;
  esac

  archive_key=$(printf '%s\n' "${archive##*/}" | sed "s/$VERSION/\" + RUST_VERSION + \"/")
  printf '        "%s": "%s",\n' "$archive_key" "$checksum" >> "$CHECKSUMS_FILE"
}

MOBILE_ARCHES="aarch64-apple-ios-sim aarch64-apple-ios x86_64-apple-ios aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android"
MOBILE_RELEASE_URL="https://github.com/bitdriftlabs/rust-std-mobile/releases/download/$VERSION"

printf '%s\n' '        # BEGIN rust-std checksums. Generated by tools/rust_std_checksum.sh.' > "$CHECKSUMS_FILE"
for arch in $MOBILE_ARCHES; do
  fetch_checksum "$MOBILE_RELEASE_URL/rust-std-$VERSION-$arch.tar.gz"
done
fetch_checksum "$MOBILE_RELEASE_URL/rust-std-tsan-$VERSION-aarch64-apple-ios-sim.tar.gz"
TSAN_CHECKSUM="$checksum"

OFFICIAL_ARCHES="aarch64-apple-darwin x86_64-unknown-linux-gnu"
for arch in $OFFICIAL_ARCHES; do
  for tool in rustc cargo llvm-tools rust-std clippy rustfmt; do
    fetch_checksum "https://static.rust-lang.org/dist/$tool-$VERSION-$arch.tar.gz"
  done
done
printf '%s\n' '        # END rust-std checksums.' >> "$CHECKSUMS_FILE"

awk \
  -v version="$VERSION" \
  -v checksums_file="$CHECKSUMS_FILE" \
  -v tsan_checksum="$TSAN_CHECKSUM" \
  '
    $0 ~ /^RUST_VERSION = "/ {
      print "RUST_VERSION = \"" version "\""
      saw_version = 1
      next
    }

    $0 ~ /^[[:space:]]*# BEGIN rust-std checksums\. Generated by tools\/rust_std_checksum\.sh\.$/ {
      while ((getline line < checksums_file) > 0) {
        print line
      }
      close(checksums_file)
      replacing_checksums = 1
      saw_checksums = 1
      next
    }

    $0 ~ /^[[:space:]]*# BEGIN rust-std-tsan checksum\. Generated by tools\/rust_std_checksum\.sh\.$/ {
      print "# BEGIN rust-std-tsan checksum. Generated by tools/rust_std_checksum.sh."
      print "RUST_IOS_TSAN_STDLIB_SHA256 = \"" tsan_checksum "\""
      print "# END rust-std-tsan checksum."
      replacing_tsan_checksum = 1
      saw_tsan_checksum = 1
      next
    }

    replacing_checksums {
      if ($0 ~ /^[[:space:]]*# END rust-std checksums\.$/) {
        replacing_checksums = 0
      }
      next
    }

    replacing_tsan_checksum {
      if ($0 ~ /^[[:space:]]*# END rust-std-tsan checksum\.$/) {
        replacing_tsan_checksum = 0
      }
      next
    }

    { print }

    END {
      if (!saw_version || !saw_checksums || !saw_tsan_checksum) {
        exit 1
      }
    }
  ' "$MODULE_FILE" > "$MODULE_FILE_TMP"

mv "$MODULE_FILE_TMP" "$MODULE_FILE"

echo "Updated MODULE.bazel for Rust $VERSION."
