name: format_check
on:
  pull_request:
# Cancel in-progress CI jobs when a new commit is pushed to a PR.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  format_check:
    runs-on: ubuntu-latest
    steps:
      # --- Build the project for release

      # Checkout repo to Github Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        id: cache-formatters
        with:
          path: ./formatters/
          key: ${{ runner.os }}-formatters-${{ hashFiles('./ci/setup_linux_format.sh') }}
      - run: ./ci/setup_linux_format.sh
        if: steps.cache-formatters.outputs.cache-hit != 'true'
      - run: |
          sudo apt-get install -y clang
          echo "CC=$(which clang)" >> $GITHUB_ENV
          echo "CXX=$(which clang++)" >> $GITHUB_ENV
        name: "Install Clang"
      - name: configure bazelrc
        run: mkdir tmp/ && echo "build --config=ci" > tmp/ci-bazelrc
      - name: test
        run: PATH=./formatters:$PATH make format
        env:
          LD_LIBRARY_PATH: ./formatters/swift/usr/lib
      - name: check diff
        run: git --no-pager diff && git diff --quiet
      - name: Check license headers
        run: ci/check_license.sh


