name: format_check
on:
  push:
    branches:
      - main
  pull_request:
# Cancel in-progress CI jobs when a new commit is pushed to a PR.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  format_check:
    runs-on: ubuntu-latest
    steps:
      # --- Build the project for release

      # Checkout repo to Github Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      - name: install formatters
        run: ./ci/setup_linux_format.sh
      - name: configure bazelrc
        run: mkdir tmp/ && echo "build --config=ci" > tmp/ci-bazelrc
      - name: test
        run: PATH=./bin:./bin:$PATH make format-ci
      - name: check diff
        run: git --no-pager diff && git diff --quiet
      - name: Check license headers
        run: ci/check_license.sh
  shellcheck:
    runs-on: ubuntu-latest-arm
    steps:
      # --- Build the project for release

      # Checkout repo to Github Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install shellcheck
        run: |
         wget -qO- "https://github.com/koalaman/shellcheck/releases/download/v0.10.0/shellcheck-v0.10.0.linux.aarch64.tar.xz" | tar -xJv
         mv "shellcheck-v0.10.0/shellcheck" shellcheck
         shellcheck --version
      - name: Run 
        run: PATH=.:$PATH make lint-shell
      - name: check diff
        run: git --no-pager diff && git diff --quiet
      - name: Check license headers
        run: ci/check_license.sh


