name: Build Android Integrations
on:
  workflow_call:
    inputs:
      version:
        description: 'The new version to tag, ex: 0.9.102'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: 'The new version to release, ex: 0.9.102'
        required: true
        type: string
jobs:
  build-gradle-libraries:
    name: Build Gradle Libraries
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./platform/jvm
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v4

    - name: Install JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: gradle
    - name: Install Rust target
      run: rustup update && rustup target add aarch64-linux-android && rustup target add x86_64-linux-android
    - name: Build Timber artifacts with Gradle
      run: ./gradlew :capture-timber:publish -PVERSION_NAME="${{ inputs.version }}" --info
      env:
        SKIP_PROTO_GEN: 1
    - name: Build Apollo artifacts with Gradle
      run: ./gradlew :capture-apollo3:publish -PVERSION_NAME="${{ inputs.version }}" --info
      env:
        SKIP_PROTO_GEN: 1
    - name: Build Gradle Plugin artifacts with Gradle
      run: ./gradlew :capture-plugin:publish -PVERSION_NAME="${{ inputs.version }}" --info
      env:
        SKIP_PROTO_GEN: 1                
    - name: Compress Timber artifacts
      run: |
        readonly dir=$(pwd)
        (cd capture-timber/build/repos/releases/io/bitdrift/capture-timber/${{ inputs.version }} && zip -r "$dir/capture-timber.zip" ./*)
    - name: Compress Apollo artifacts
      run: |
        readonly dir=$(pwd)
        (cd capture-apollo3/build/repos/releases/io/bitdrift/capture-apollo3/${{ inputs.version }} && zip -r "$dir/capture-apollo3.zip" ./*)        
    - name: Compress Android Plugin artifacts
      run: |
        readonly dir=$(pwd)
        (cd capture-plugin/build/repos/releases/io/bitdrift/capture-plugin/${{ inputs.version }} && zip -r "$dir/capture-plugin.zip" ./*)
    - name: Upload Timber artifacts
      uses: actions/upload-artifact@v4
      with:
        name: capture-timber.zip
        path: platform/jvm/capture-timber.zip
        if-no-files-found: error
    - name: Upload Apollo artifacts
      uses: actions/upload-artifact@v4
      with:
        name: capture-apollo3.zip
        path: platform/jvm/capture-apollo3.zip
        if-no-files-found: error        
    - name: Upload Gradle Plugin artifacts
      uses: actions/upload-artifact@v4
      with:
        name: capture-plugin.zip
        path: platform/jvm/capture-plugin.zip
        if-no-files-found: error
