name: Build iOS Integrations
on:
  workflow_call:
    inputs:
      version:
        description: 'The new version to tag, ex: 0.9.102'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: 'The new version to release, ex: 0.9.102'
        required: true
        type: string
jobs:
  build-capture-extensions:
    name: CaptureExtensions
    runs-on: macos-14
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: 'Install dependencies'
        run: ./ci/mac_ci_setup.sh
      - name: Build CaptureExtensions.xcframework
        run: ./tools/ios_release.sh CaptureExtensions ${{ inputs.version }}
      - uses: actions/upload-artifact@v4
        with:
          name: CaptureExtensions.ios
          path: ./dist/CaptureExtensions.ios.zip
