name: ios
on:
  push:
    branches:
      - main
  pull_request:
# Cancel in-progress CI jobs when a new commit is pushed to a PR.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  test_release:
    name: test_release
    runs-on: macos-15
    steps:
      # Checkout repo to Github Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Install dependencies"
        run: ./ci/mac_ci_setup.sh

      - name: "Build app"
        run: |
          ./tools/ios_release.sh
          ls -la dist/Capture.ios.zip
          unzip -lv dist/Capture.ios.zip
          sha256sum dist/Capture.ios.zip

      - uses: actions/upload-artifact@v4
        with:
          name: Capture.ios.zip
          path: ./dist/Capture.ios.zip
