name: Testing

on:
  pull_request:

jobs:
  update-sdk-version:
    name: Update SDK version
    needs: public-release
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # Checkout repo to Github Actions runner
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Update the content of platform/shared/.sdk_version'
        run: |
          echo -n '${{ inputs.version }}' > $file
          echo "Updated content of '$file' file:"
          cat $file
        env:
          file: 'platform/shared/.sdk_version'

      - name: 'Create Github Token'
        id: org-pr-create-token
        uses: getsentry/action-github-app-token@d4b5da6c5e37703f8c3b3e43abb5705b46e159cc # v3.0.0
        with:
          app_id: ${{ secrets.OPEN_CAPTURE_SDK_PRS_APP_ID }}
          private_key: ${{ secrets.OPEN_CAPTURE_SDK_PRS_PRIVATE_KEY }}

      - name: 'Commiting the changes'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git \
            -c author.name="${{ github.actor }}" \
            -c author.email="${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com" \
            -c user.name="GitHub Action" \
            -c user.email="noreply@github.com" \
            commit \
            -am 'Update SDK version to ${{ inputs.version }}'
          git push origin
